### ISSUE TITLE
Outputs ROMs into subfolders

### ISSUE THREAD

**Issue by dinsdalepiranha** [andrebrait/DATROMTool#2]
Processing the [same FBneo DAT as this user](https://github.com/andrebrait/1g1r-romset-generator/issues/21) and it seems DATROMTool always leaves the processed ROMs in sub-directories that do not exist in the source files.

So if the source ROM is like this:

./in-dir/romname.zip

The output of DATROMTool is like this:

./out-dir/romname/romname.zip

I am using your RC2 release tag with OpenJDK 11.0.16 and *not* specifying --force-subfolder

**Comment by andrebrait** [comment]
If the source ROM is composed of multiple files and you're not using an
archive format for it, that's expected.

Could you send me the DAT you're using and the full command line?

Andre Brait

**Comment by dinsdalepiranha** [comment]
> Could you send me the DAT you're using and the full command line?

Emailed.  You might need to check spam.

**Comment by andrebrait** [comment]
Ok, I think it's a bug I have already fixed but for some reason is still in
RC2. I'll do an RC3 when I have the chance or you can gran the code and
build it with JDK17 and Maven.

Btw, each excluded word needa its own exclude option.

```
--exclude="Mahjong,Poker,Cassette,Multigame,Multivideo,Multi " \
```

should be

```
--exclude "Mahjong" \
--exclude "Poker" \
--exclude "Cassette" \
--exclude "Multigame" \
--exclude "Multivideo" \
--exclude "Multi" \
```

Andre Brait

**Comment by andrebrait** [comment]
Ok, I think it's a bug I have already fixed but for some reason is still in
RC2. I'll do an RC3 when I have the chance or you can gran the code and
build it with JDK17 and Maven.

Btw, each excluded word needs its own exclude option.

```sh
--exclude="Mahjong,Poker,Cassette,Multigame,Multivideo,Multi "
```

should be

```sh
--exclude "Mahjong" \
--exclude "Poker" \
--exclude "Cassette" \
--exclude "Multigame" \
--exclude "Multivideo" \
--exclude "Multi"
```

**Comment by dinsdalepiranha** [comment]
> Btw, each excluded word needs its own exclude option.

Looking at this closely I found that even when separating the --exclude arguments they appear to be disregarded by DATROMTool.  For example, this game is still present in the processed ROMs:

```
        <game name="cultures">
                <description>Jibun wo Migaku Culture School Mahjong Hen</description>
                <year>1994</year>
                <manufacturer>Face</manufacturer>
                <rom name="ma01.u12" size="262144" crc="f57417b3"/>
                <rom name="bg0c.u45" size="2097152" crc="ad2e1263"/>
                <rom name="bg0c2.u46" size="1048576" crc="97c71c09"/>
                <rom name="bg2c.u68" size="2097152" crc="fa598644"/>
                <rom name="bg1t.u67" size="1048576" crc="d2e594ee"/>
                <rom name="bg1c.u80" size="2097152" crc="9ab99bd9"/>
                <rom name="bg2t.u79" size="1048576" crc="0610a79f"/>
                <rom name="pcm.u87" size="2097152" crc="84206475"/>
                <video type="raster" orientation="horizontal" width="384" height="240" aspectx="4" aspecty="3"/>
                <driver status="good"/>
        </game>
```
Am I misunderstanding how this feature works?

**Comment by andrebrait** [comment]
Hm, that's likely a recent change on DATs. By default, only the `name` attribute is evaluated. Same thing goes for deciding file names and whatnot.

The name doesn't contain Mahjong. The description does.

**Comment by andrebrait** [comment]
Well, I mean, those DATs use the name differently, but I think I've seen Retool do a change similar to this, so I'm gonna add the description field as a valid source for filtering.
